[package]
name = "redact-store"
version = "0.1.17"
authors = ["ajp <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
rust-config = { git = "https://github.com/ajpauwels/rust-config.git", rev = "f5d30659eba5cbcf57941414ddc79a19dfcf1110" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = "1.1.1"
bson = "1.1.0"
futures = "0.3.8"
pretty_env_logger = "0.4"
