[package]
name = "redact-store"
version = "0.1.0"
authors = ["ajp <8890201+ajpauwels@users.noreply.github.com>"]
edition = "2018"
license-file = "LICENSE"
description = "Provides a common interface on top of storage backings"
documentation = "https://docs.rs/redact-store"
repository = "https://github.com/pauwels-labs/redact-store.git"
readme = "README.md"
exclude = [
        ".dockerignore",
        ".git",
        ".gitignore",
        ".lighthouse",
        "charts",
        "preview",
        "Dockerfilest",
        "Dockerfilest.dev",
        "Dockerfilest.test",
        "OWNERS",
        "OWNERS_ALIASES",
        "tarpaulin-report.html"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
redact-config = { git = "https://github.com/pauwels-labs/redact-config.git", rev = "392bffd9e83e1d3a055fa9b047d8da62a7e2a393" }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
mongodb = "1.2.1"
bson = "1.1.0"
futures = "0.3.8"
pretty_env_logger = "0.4"
async-trait = "0.1.42"
async-recursion = "0.3.2"
redact-crypto = { git = "https://github.com/pauwels-labs/redact-crypto.git", rev = "e1806d49d12fa9722e389432e8cf57cd80267b3c" }
